# Generated by Django 2.2.5 on 2019-09-04 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rubrica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubrica',
            name='usuario',
        ),
    ]
