# Generated by Django 2.2.4 on 2019-09-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrica', '0004_auto_20190904_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
